repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml

    -   id: end-of-file-fixer
        name: Check and fix end-of-file markers

    -   id: trailing-whitespace
        name: Check and remove trailing whitespace

    - id: pretty-format-json
      name: Make pretty json
      args: [ --autofix, --no-ensure-ascii, --no-sort-keys ]


-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.1
    hooks:
    -   id: poetry-check
        name: Check and fix end-of-file markers


-   repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
        - id: yapf
          name: Formatter (yapf)
          args: [
            '--style=code_checkers/.style.yapf',
            '--parallel',
            '--in-place',
            '--recursive',
            '--verbose',
            'app/',
          ]
          language_version: python3.11


-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Linter (flake8)
        args: [--config=code_checkers/.flake8, app]
        additional_dependencies:
          - flake8-bugbear
          - flake8-import-order
          - flake8-docstrings
          - flake8-quotes
          - flake8-commas
          - flake8-builtins
        language_version: python3.11


-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Secure check by bandit
        args: ['-c', 'code_checkers/bandit.yaml']
