version: '3'

services:
  django:
    container_name: prod-referral-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    command: gunicorn --chdir app config.wsgi:application --bind 0.0.0.0:8000
    volumes:
       - ./persistentdata/static:/home/unprivilegeduser/ref_api/static
    expose:
      - 8000
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    container_name: prod-postgres-15.3
    image: postgres:15.3
    env_file:
      - env/.env.db
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/

  redis:
    container_name: prod-redis-7.0.5-alpine
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    container_name: prod-celery
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    environment:
      - REDIS_HOST=redis
    entrypoint: celery
    command: --workdir=./app -A config worker --loglevel=info
    depends_on:
      - redis

  nginx:
    restart: always
    container_name: prod-nginx-1.25
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./persistentdata/static:/home/unprivilegeduser/ref_api/static
    depends_on:
      - django
