version: '3'

services:
  django:
    container_name: local-referral-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    command: sh -c "
      python app/manage.py makemigrations &&
      python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/home/app/referral
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    container_name: local-postgres-15.3
    image: postgres:15.3
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: local-redis-7.0.5-alpine
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    container_name: local-celery
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    environment:
      - REDIS_HOST=redis
    entrypoint: celery
    command: --workdir=./app -A config worker --loglevel=info
    volumes:
      - .:/home/app/referral
    depends_on:
      - redis

  flower:
    container_name: local-flower
    build:
      context: .
      dockerfile: Dockerfile
    hostname: flower
    entrypoint: celery
    command: --workdir=./app -A config flower
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
