# Generated by Django 4.2.4 on 2023-08-10 13:40

from django.db import migrations, models
import referrals.referral_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=referrals.referral_services.generate_referral_code, max_length=6, verbose_name='Referral code')),
            ],
            options={
                'verbose_name': 'Referral code',
                'verbose_name_plural': 'Referral codes',
            },
        ),
    ]
