name: Basic code style & code secure checks

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Update pip and Install poetry
        run:  |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Poetry install (only dev dependencies)
        run: poetry install --only dev

      - name: Run flake8 from poetry
        run: poetry run flake8 --config=style/.flake8 app

      - name: Run bandit from poetry
        run: poetry run bandit -r -c style/bandit.yaml app
